
ALTER TABLE match ALTER COLUMN match_date SET NOT NULL;
ALTER TABLE match ALTER COLUMN match_time SET NOT NULL;
ALTER TABLE match ALTER COLUMN team_a SET NOT NULL;
ALTER TABLE match ALTER COLUMN team_b SET NOT NULL;
ALTER TABLE match ALTER COLUMN sport SET NOT NULL;



ALTER TABLE match_odds ALTER COLUMN specifier SET NOT NULL;
ALTER TABLE match_odds ALTER COLUMN odd SET NOT NULL;